<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;
use Exception;
class FileController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     */
    public function show(string $id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, string $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(string $id)
    {
        //
    }

    public function uploadIndependent(Request $request)
    {
        $request->validate([
            'file' => 'required|file|max:20480|mimes:pdf,doc,docx,txt,png,jpg,jpeg,webp,gif',
        ]);

        if ($request->hasFile('file')) {
            $file = $request->file('file');
            $extension = $file->getClientOriginalExtension();
            $safeFileName = (string) \Illuminate\Support\Str::uuid() . '_' . time() . '.' . $extension;
            
            try {
                $path = $file->storeAs('uploads', $safeFileName, 'public');

                // Create DB entry with NULL note_id initially
                $fileRecord = \App\Models\File::create([
                    'file_path' => $path,
                    'type' => $extension,
                    'note_id' => null, 
                ]);

                return response()->json([
                    'message' => 'File uploaded',
                    'file_id' => $fileRecord->file_id, 
                    'file_url' => \Illuminate\Support\Facades\Storage::url($path),
                ], 200);

            } catch (\Exception $e) {
                return response()->json(['message' => 'Upload failed: ' . $e->getMessage()], 500);
            }
        }
        return response()->json(['message' => 'No file received.'], 400);
    }

    /**
     * Handle multiple files and a markdown file upload in one request.
     * Route: POST /api/files/upload-batch
     */
    public function uploadBatch(Request $request)
    {
        // 1. Validate the incoming request
        $request->validate([
            // 'attachments' must be an array of files
            'attachments' => 'nullable|array', 
            'attachments.*' => 'file|max:20480|mimes:pdf,doc,docx,txt,png,jpg,jpeg,webp', 
            
            // 'note_file' is the specific markdown file generated by Flutter
            'note_file' => 'nullable|file|max:10240|mimes:md,txt,markdown', 
        ]);

        $response = [
            'message' => 'Upload processing complete',
            'markdown_data' => null,
            'attachments_data' => [],
        ];

        try {
            // --- A. Handle the Markdown File ---
            if ($request->hasFile('note_file')) {
                $mdFile = $request->file('note_file');
                
                // Generate safe name: note_timestamp_random.md
                $mdName = 'note_' . time() . '_' . Str::random(8) . '.md';
                
                // Store in a specific 'notes' folder
                $mdPath = $mdFile->storeAs('notes', $mdName, 'public');

                $response['markdown_data'] = [
                    'original_name' => $mdFile->getClientOriginalName(),
                    'stored_name' => $mdName,
                    'file_url' => Storage::url($mdPath),
                    'file_path' => $mdPath, // Internal path for DB saving
                ];
            }

            // --- B. Handle Multiple Attachments ---
            if ($request->hasFile('attachments')) {
                foreach ($request->file('attachments') as $file) {
                    // Generate unique name
                    $extension = $file->getClientOriginalExtension();
                    $safeFileName = (string) Str::uuid() . '_' . time() . '.' . $extension;

                    // Store in 'uploads' folder
                    $path = $file->storeAs('uploads', $safeFileName, 'public');

                    // Add to response array
                    $response['attachments_data'][] = [
                        'original_name' => $file->getClientOriginalName(),
                        'file_url' => Storage::url($path),
                        'file_path' => $path,
                    ];

                    // OPTIONAL: If you use the 'File' model, save to DB here
                    /*
                    File::create([
                        'file_path' => $path,
                        'file_name' => $file->getClientOriginalName(),
                        'type' => $extension,
                    ]);
                    */
                }
            }

            return response()->json($response, 200);

        } catch (Exception $e) {
            return response()->json([
                'message' => 'Batch upload failed',
                'error' => $e->getMessage()
            ], 500);
        }
    }

    /**
     * Single file upload (Keep your existing one for backward compatibility if needed)
     */
    public function upload(Request $request)
    {
        $request->validate([
            'file' => 'required|file|max:20480|mimes:pdf,doc,docx,txt,png,jpg,jpeg', 
        ]);

        if ($request->hasFile('file')) {
            $file = $request->file('file');
            $originalName = $file->getClientOriginalName();
            $safeFileName = (string) Str::uuid() . '_' . time() . '.' . $file->getClientOriginalExtension();

            try {
                $path = $file->storeAs('uploads', $safeFileName, 'public');
                return response()->json([
                    'message' => 'File uploaded successfully',
                    'original_name' => $originalName,
                    'file_url' => Storage::url($path), 
                    'file_path' => $path,
                ], 200);

            } catch (Exception $e) {
                return response()->json(['message' => 'File upload failed: ' . $e->getMessage()], 500);
            }
        }

        return response()->json(['message' => 'No file received.'], 400);
    }

    /**
     * Delete a file
     */
    public function delete(Request $request)
    {
        $filePath = $request->input('file_path'); 
        
        if ($filePath && Storage::disk('public')->exists($filePath)) {
            Storage::disk('public')->delete($filePath);
            return response()->json(['message' => 'File deleted successfully'], 200);
        }
        
        return response()->json(['message' => 'File not found'], 404);
    }
}
