<?php

namespace App\Http\Controllers\Api\V1;

use App\Http\Controllers\Controller;
use App\Models\Achievement;
use Illuminate\Http\Request;
use Illuminate\Http\JsonResponse;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Str;

/**
 * Controller for managing Achievement resources via API, intended for consumption by mobile clients like Flutter.
 */
class AchievementController extends Controller
{
    /**
     * Display a listing of the resource.
     * Fetches all achievements and returns them as a JSON array.
     *
     * @return JsonResponse
     */
    public function index(): JsonResponse
    {
        try {
            // Fetch achievements, ordering by the UUIDv7 for approximate creation time
            $achievements = Achievement::orderBy('achievement_id')->get();

            return response()->json([
                'status' => 'success',
                'message' => 'Achievements fetched successfully.',
                'data' => $achievements
            ], 200);

        } catch (\Exception $e) {
            Log::error("Failed to fetch achievements: " . $e->getMessage());
            return response()->json([
                'status' => 'error',
                'message' => 'Could not retrieve achievements.',
                'error_details' => $e->getMessage()
            ], 500);
        }
    }

    /**
     * Store a newly created resource in storage.
     * Handles POST request from Flutter to create a new achievement.
     *
     * @param Request $request
     * @return JsonResponse
     */
    public function store(Request $request): JsonResponse
    {
        // 1. Validate the incoming request data
        $validator = Validator::make($request->all(), [
            'achievement_name' => 'required|string|max:255',
            'title' => 'required|string|max:255',
            'description' => 'nullable|string',
            'type' => 'required|string|max:50',
            // Ensure these UUIDs are valid CHAR(36) strings
            'level_id' => 'required|string|uuid|exists:levels,level_id',
            'created_by' => 'required|string|uuid|exists:users,id', // Assuming 'users.id' is the column
        ]);

        if ($validator->fails()) {
            return response()->json([
                'status' => 'error',
                'message' => 'Validation failed.',
                'errors' => $validator->errors()
            ], 422);
        }

        try {
            // 2. Create the Achievement (UUIDv7 for achievement_id is auto-generated by HasUuids trait)
            $achievement = Achievement::create($validator->validated());

            return response()->json([
                'status' => 'success',
                'message' => 'Achievement created successfully.',
                'data' => $achievement
            ], 201); // 201 Created

        } catch (\Exception $e) {
            Log::error("Failed to create achievement: " . $e->getMessage());
            return response()->json([
                'status' => 'error',
                'message' => 'Could not create achievement.',
                'error_details' => $e->getMessage()
            ], 500);
        }
    }

    /**
     * Display the specified resource.
     *
     * @param string $achievement_id
     * @return JsonResponse
     */
    public function show(string $achievement_id): JsonResponse
    {
        try {
            // Use findOrFail to automatically handle 404
            $achievement = Achievement::findOrFail($achievement_id);

            return response()->json([
                'status' => 'success',
                'message' => 'Achievement retrieved successfully.',
                'data' => $achievement
            ], 200);

        } catch (\Exception $e) {
            return response()->json([
                'status' => 'error',
                'message' => 'Achievement not found.',
                'error_details' => $e->getMessage()
            ], 404);
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param Request $request
     * @param string $achievement_id
     * @return JsonResponse
     */
    public function update(Request $request, string $achievement_id): JsonResponse
    {
        // 1. Validate the incoming request data
        $validator = Validator::make($request->all(), [
            'achievement_name' => 'sometimes|required|string|max:255',
            'title' => 'sometimes|required|string|max:255',
            'description' => 'nullable|string',
            'type' => 'sometimes|required|string|max:50',
            'level_id' => 'sometimes|required|string|uuid|exists:levels,level_id',
            'created_by' => 'sometimes|required|string|uuid|exists:users,id',
        ]);

        if ($validator->fails()) {
            return response()->json([
                'status' => 'error',
                'message' => 'Validation failed.',
                'errors' => $validator->errors()
            ], 422);
        }

        try {
            $achievement = Achievement::findOrFail($achievement_id);
            $achievement->update($validator->validated());

            return response()->json([
                'status' => 'success',
                'message' => 'Achievement updated successfully.',
                'data' => $achievement
            ], 200);

        } catch (\Exception $e) {
            Log::error("Failed to update achievement (ID: {$achievement_id}): " . $e->getMessage());
            return response()->json([
                'status' => 'error',
                'message' => 'Could not update achievement.',
                'error_details' => $e->getMessage()
            ], 500);
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param string $achievement_id
     * @return JsonResponse
     */
    public function destroy(string $achievement_id): JsonResponse
    {
        try {
            $deleted = Achievement::destroy($achievement_id);

            if (!$deleted) {
                 return response()->json([
                    'status' => 'error',
                    'message' => 'Achievement not found.',
                ], 404);
            }

            return response()->json([
                'status' => 'success',
                'message' => 'Achievement deleted successfully.'
            ], 204); // 204 No Content

        } catch (\Exception $e) {
            Log::error("Failed to delete achievement (ID: {$achievement_id}): " . $e->getMessage());
            return response()->json([
                'status' => 'error',
                'message' => 'Could not delete achievement.',
                'error_details' => $e->getMessage()
            ], 500);
        }
    }
}